name: cnss_allocpren_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # --- DÉPENDANCES DE BASE ---
  get: ^4.6.6
  google_fonts: ^6.2.1
  file_picker: ^8.0.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3

  # --- DÉPENDANCES FIREBASE ---
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5

  # --- DÉPENDANCE POUR LES GRAPHIQUES ---
  fl_chart: ^0.68.0

  # --- DÉPENDANCES POUR L'EXPORT ET L'IMPRESSION ---
  pdf: ^3.10.8
  printing: ^5.12.0
  # NOUVELLE DÉPENDANCE POUR EXCEL/CSV
  csv: ^5.1.1
  # --- FIN DE L'AJOUT ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true