// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIHn8K_x4xVhQYoudqhsgFulusbqEL4vA',
    appId: '1:96373236347:web:4fbda5008611b9b97b78de',
    messagingSenderId: '96373236347',
    projectId: 'cnss-allocations-app',
    authDomain: 'cnss-allocations-app.firebaseapp.com',
    storageBucket: 'cnss-allocations-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2SwMt_DFNUdU0DRrux9vNFgnjzDoKoKk',
    appId: '1:96373236347:android:d312b9f3a48a138e7b78de',
    messagingSenderId: '96373236347',
    projectId: 'cnss-allocations-app',
    storageBucket: 'cnss-allocations-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADADFEUY15eb3WkFYMW5s2k-c0B9Kkcbc',
    appId: '1:96373236347:ios:b5c30b8a4ced78467b78de',
    messagingSenderId: '96373236347',
    projectId: 'cnss-allocations-app',
    storageBucket: 'cnss-allocations-app.firebasestorage.app',
    iosBundleId: 'com.example.cnssAllocprenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADADFEUY15eb3WkFYMW5s2k-c0B9Kkcbc',
    appId: '1:96373236347:ios:b5c30b8a4ced78467b78de',
    messagingSenderId: '96373236347',
    projectId: 'cnss-allocations-app',
    storageBucket: 'cnss-allocations-app.firebasestorage.app',
    iosBundleId: 'com.example.cnssAllocprenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIHn8K_x4xVhQYoudqhsgFulusbqEL4vA',
    appId: '1:96373236347:web:e781201306d7a4007b78de',
    messagingSenderId: '96373236347',
    projectId: 'cnss-allocations-app',
    authDomain: 'cnss-allocations-app.firebaseapp.com',
    storageBucket: 'cnss-allocations-app.firebasestorage.app',
  );
}
